.TH YED-CUSTOM_FRAMES 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
custom_frames \- Gives a configurable framework to attach custom frames and special animations to special buffers
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
custom_frames, custom, frame, special, buffers, animations
